version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/docker-entrypoint-initdb.d/db_data
    environment:
      POSTGRES_DB: movielens
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  ml_model:
    build: ./ml_model
    volumes:
      - ./ml_model:/app
    environment:
      DATABASE_URL: postgresql://user:password@db/movielens
    depends_on:
      - db

volumes:
  dbdata:
